### ISSUE TITLE
LoadError: The RubyEncoder loader is not installed.

### ISSUE THREAD

**Issue by YowFung** [YowFung/me#20]
在对 redmine 系统进行升级的过程中，执行数据库迁移的命令 `bundle exec rake db:migrate RAILS_ENV=production` 时报错，报错信息如下：
```log
root@a9d7baa4ce4c:/usr/local/redmine-4.1.3# bundle exec rake db:migrate RAILS_ENV=production
rake aborted!
LoadError: The RubyEncoder loader is not installed. Please visit the http://www.rubyencoder.com/loaders/ RubyEncoder site to download the required loader for 'linux' and unpack it into '/usr/local/redmine-4.1.3/plugins/redmine_issue_autoflow/rgloader' directory
to run this protected script.
/usr/local/redmine-4.1.3/plugins/redmine_issue_autoflow/rgloader/loader.rb:22:in `<top (required)>'
/usr/local/redmine-4.1.3/plugins/redmine_issue_autoflow/lib/redmine_issue_autoflow/redmine_issue_autoflow.rb:2:in `<top (required)>'
/usr/local/redmine-4.1.3/plugins/redmine_issue_autoflow/init.rb:2:in `<top (required)>'
/usr/local/redmine-4.1.3/lib/redmine/plugin.rb:181:in `block in load'
/usr/local/redmine-4.1.3/lib/redmine/plugin.rb:172:in `each'
/usr/local/redmine-4.1.3/lib/redmine/plugin.rb:172:in `load'
/usr/local/redmine-4.1.3/config/initializers/30-redmine.rb:20:in `<top (required)>'
/usr/local/redmine-4.1.3/config/environment.rb:16:in `<top (required)>'
/usr/local/redmine-4.1.3/bin/bundle:4:in `load'
/usr/local/redmine-4.1.3/bin/bundle:4:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by YowFung** [comment]
关键信息：
```txt
LoadError: The RubyEncoder loader is not installed. Please visit the http://www.rubyencoder.com/loaders/ RubyEncoder site to download the required loader for 'linux' and unpack it into '/usr/local/redmine-4.1.3/plugins/redmine_issue_autoflow/rgloader' directory
to run this protected script.
```

根据提示打开 http://www.rubyencoder.com/loaders/ RubyEncoder 网站并下载 RubyEncoder 装载器，然后解压到 `/usr/local/redmine-4.1.1/plugins/redmine_issue_autoflow/rgloader` 目录中。

**Comment by YowFung** [comment]
或者按照 `Redmine Issue Autoflow` 插件官方的[安装指引](https://redmineplugins.cn/projects/1/plugin_blocks/36?tab=installation_notes)来执行安装该插件需要的其他命令。

**Comment by YowFung** [comment]
如果还是出现问题，则请检查 ruby 版本以及插件版本是否兼容。
