### ISSUE TITLE
can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by YowFung** [YowFung/me#21]
升级 ruby 到 2.7.0 后，运行 `pod update Firebase/CoreOnly` 命令，得到以下这样的报错信息：
```log
❯ pod update Firebase/CoreOnly                                                                                                                                           ─╯
Traceback (most recent call last):
        2: from /usr/local/bin/pod:23:in `<main>'
        1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
```

**Comment by YowFung** [comment]
重新安装 cocoapods：
```shell
sudo gem install -n /usr/local/bin cocoapods
```
*如果安装了多个 XCode，可以使用下面的命令选择（一般需要选择最近的 XCode 版本）：*
```shell
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```
安装本地库：
```shell
pod setup
```

------
> 参考资料：[《CocoaPods安装方法-2021.05.01》](https://www.jianshu.com/p/f43b5964f582)
