### ISSUE TITLE
Flutter for Android 编译报错：`Permission Denial: starting Intent { ... } from null (...) not exported from uid xxx`

### ISSUE THREAD

**Issue by YowFung** [YowFung/me#51]
执行 Gradle 编译任务的时候报如下错误：

```txt
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
ProcessException: Process exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.proitav.vdirector/.MainActivity (has extras) }


Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.proitav.vdirector/.MainActivity (has extras) } from null (pid=10767, uid=2000) not exported from uid 10148
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1059)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:981)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:670)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1223)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1195)
	at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:2949)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:201)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:8646)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5163)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2516)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
  Command: /Users/yowfung/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.proitav.vdirector/com.proitav.vdirector.MainActivity
```

**Comment by YowFung** [comment]
网上有人说是 `AndroidManifest.xml` 中把 `android:name=".MainActivity"` 多写两次，也有人说是 `AndroidManifest.xml` 中尖括号不匹配。以上这些情况我都检查了，都没问题，但编译仍然报这个错误。
